# Generated by Django 4.2.8 on 2023-12-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано в')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено в')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено?')),
                ('parent', models.ForeignKey(blank=True, help_text='Пустое значение означает, что родительского нет', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment', verbose_name='Родительский коммент')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
